### ISSUE TITLE
FileExistError exception thrown on repeated runs

### ISSUE THREAD

**Issue by sriyerg** [olofk/fusesoc#357]
When running sims repeatedly without cleaning the build area, I see the following exception thrown:

```console
Traceback (most recent call last):
  File "/usr/local/google/home/sriyer/.local/bin/fusesoc", line 10, in <module>
    sys.exit(main())
  File "/usr/local/google/home/sriyer/.local/lib/python3.7/site-packages/fusesoc/main.py", line 583, in main
    args.func(cm, args)
  File "/usr/local/google/home/sriyer/.local/lib/python3.7/site-packages/fusesoc/main.py", line 268, in run
    flags, args.system_name, args.system, args.backendargs, args.build_root)
  File "/usr/local/google/home/sriyer/.local/lib/python3.7/site-packages/fusesoc/main.py", line 316, in run_backend
    system_name=system_name)
  File "/usr/local/google/home/sriyer/.local/lib/python3.7/site-packages/fusesoc/edalizer.py", line 53, in __init__
    core.export(files_root, _flags)
  File "/usr/local/google/home/sriyer/.local/lib/python3.7/site-packages/fusesoc/capi2/core.py", line 183, in export
    os.makedirs(os.path.join(dst_dir, d))
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'scratch/top_earlgrey.sim.vcs/top_sanity/default/src/lowrisc_systems_top_earlgrey_0.1/../ip/alert_handler/rtl'
```
A quick fix for this is to simply set `exist_ok=True` flag to `os.makedirs()` in `fusesoc/capi2/core.py` :: line 183.

**Comment by sriyerg** [comment]
Fixed this issue by better reorganizing the sources in the core files (ensuring core files do not include sources from a different directory tree.)
