### ISSUE TITLE
AttributeError: class Section has no attribute '__subclasses__'

### ISSUE THREAD

**Issue by NeilDegruthTR** [olofk/fusesoc#437]
Hi,
I was trying to install fusesoc but whenever I write commands about fusesoc, I encounter with this error:
`Traceback (most recent call last):

File "/usr/local/bin/fusesoc", line 9, in <module>
    load_entry_point('fusesoc==1.11.0', 'console_scripts', 'fusesoc')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/fusesoc/main.py", line 22, in <module>
    from fusesoc.coremanager import CoreManager, DependencyError
  File "/usr/local/lib/python2.7/dist-packages/fusesoc/coremanager.py", line 17, in <module>
    from fusesoc.core import Core
  File "/usr/local/lib/python2.7/dist-packages/fusesoc/core.py", line 7, in <module>
    from fusesoc.capi1.core import Core as Capi1Core
  File "/usr/local/lib/python2.7/dist-packages/fusesoc/capi1/core.py", line 15, in <module>
    from fusesoc.capi1 import section
  File "/usr/local/lib/python2.7/dist-packages/fusesoc/capi1/section.py", line 825, in <module>
    _register_subclasses(Section)
  File "/usr/local/lib/python2.7/dist-packages/fusesoc/capi1/section.py", line 818, in _register_subclasses
    for cls in parent.__subclasses__():
AttributeError: class Section has no attribute '__subclasses__'
`

I'm not good at software developing. So, what should i do to install properly fusesoc?

**Comment by imphil** [comment]
You are using FuseSoC 1.11 with Python 2.7, which is not supported.

* If you want to use the latest version of fusesoc, you need to use Python 3.5+ (recommended). Typically, you can use `pip3 install fusesoc` to get a version of FuseSoC installed for Python 3.
* If you need to use Python 2.7 you can install FuseSoC 1.10 with `pip install fusesoc==1.10`. Note that Python 2 is end of life since almost a year now and you really should switch to Python 3.

Before you do any of that uninstall FuseSoC with `pip uninstall fusesoc`.
