### ISSUE TITLE
Issue with SECTION_MAP attribute

### ISSUE THREAD

**Issue by juliusbaxter** [olofk/fusesoc#54]
I've just updated to 15cf8143c30b4bb and I am seeing the following:

<pre>
$ fusesoc list-cores
Traceback (most recent call last):
  File "/home/jules/git/fusesoc/bin/fusesoc", line 232, in <module>
    run(parsed_args)
  File "/home/jules/git/fusesoc/bin/fusesoc", line 167, in run
    cm.add_cores_root(config.cores_root)
  File "/home/jules/git/fusesoc/fusesoc/coremanager.py", line 64, in add_cores_root
    self.load_cores(os.path.expanduser(p))
  File "/home/jules/git/fusesoc/fusesoc/coremanager.py", line 53, in load_cores
    self.load_core(d, f)
  File "/home/jules/git/fusesoc/fusesoc/coremanager.py", line 30, in load_core
    self._cores[name] = Core(file)
  File "/home/jules/git/fusesoc/fusesoc/core.py", line 34, in __init__
    for s in section.SECTION_MAP:
AttributeError: 'module' object has no attribute 'SECTION_MAP'
</pre>

By following the helpful advice of stekern [here](http://juliusbaxter.net/openrisc-irc/%23openrisc.2014-05-30.log.html#t13:25) I was able to get this to work again. So I did something like:

<pre>
$ make distclean
$ find . -name "*.pyc" | xargs rm
</pre>

.. and list-cores worked again. However, probably the root cause of this should be identified?

Not sure if this is Python issue or what, but maybe a clean should clear away .pycs?

**Comment by olofk** [comment]
Closing now
