### ISSUE TITLE
ValueError: Invalid preamble: 'pulp__platform.org__axi 0.35.2-dev-0'

### ISSUE THREAD

**Issue by skokvermon** [olofk/fusesoc#563]
Hello

I tried to add pulp-platform axi core as a local library. The problem is that the version is 0.35.2-dev-0 which format doesn't match fusesoc.
Maybe some filtering would be needed to avoid the error message.

to reproduce:
`fusesoc library add axi https://github.com/pulp-platform/axi.git`

```
$ fusesoc core list

Available cores:

Core                               Cache status  Description
================================================================================
pulp-platform.org::axi:0.35.2-dev :      local : <No description>
```

```
$ fusesoc core show pulp-platform.org::axi
preamble pulp__platform.org__axi 0.35.2-dev-0
Traceback (most recent call last):
  File "/home/skok/.local/bin/fusesoc", line 11, in <module>
    load_entry_point('fusesoc', 'console_scripts', 'fusesoc')()
  File "/home/skok/pkgs/fusesoc/fusesoc/main.py", line 695, in main
    fusesoc(args)
  File "/home/skok/pkgs/fusesoc/fusesoc/main.py", line 685, in fusesoc
    args.func(cm, args)
  File "/home/skok/pkgs/fusesoc/fusesoc/main.py", line 240, in core_info
    core = _get_core(cm, args.core)
  File "/home/skok/pkgs/fusesoc/fusesoc/main.py", line 40, in _get_core
    core = cm.get_core(Vlnv(name))
  File "/home/skok/pkgs/fusesoc/fusesoc/coremanager.py", line 333, in get_core
    c = self.db.find(name)
  File "/home/skok/pkgs/fusesoc/fusesoc/coremanager.py", line 80, in find
    found = self._solve(vlnv, only_matching_vlnv=True)[-1]
  File "/home/skok/pkgs/fusesoc/fusesoc/coremanager.py", line 165, in _solve
    package = parser.parse_to_package(package_str)
  File "/home/skok/.local/lib/python3.8/site-packages/simplesat/constraints/package_parser.py", line 89, in parse_to_package
    pkg_dict = self.parse(package_string)
  File "/home/skok/.local/lib/python3.8/site-packages/simplesat/constraints/package_parser.py", line 70, in parse
    distribution, version = _parse_preamble(preamble)
  File "/home/skok/.local/lib/python3.8/site-packages/simplesat/constraints/package_parser.py", line 137, in _parse_preamble
    raise ValueError(msg)
ValueError: Invalid preamble: 'pulp__platform.org__axi 0.35.2-dev-0'
```

**Comment by skokvermon** [comment]
I could manage to workaround this by changing the core file in axi and set the name without a - in the core file.
